language: node_js
sudo: false
node_js: 10
cache:
  directories:
    - node_modules
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh ./scripts/deploy.sh
  on:
    branch: master
