language: node_js
sudo: false
node_js: 10
cache:
  directories:
    - node_modules
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
  - gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "bridetool-website"
  local_dir: public
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
